/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.protokit.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ProtokitDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("hu/bme/aut/protokit/parser/antlr/internal/InternalProtokitDSL.tokens");
	}
}
