/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.protokit.ui.tests;

import com.google.inject.Injector;
import hu.bme.aut.protokit.lang.ui.internal.LangActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class ProtokitDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LangActivator.getInstance().getInjector("hu.bme.aut.protokit.ProtokitDSL");
	}

}
