/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.protokit.ui;

import com.google.inject.Injector;
import hu.bme.aut.protokit.lang.ui.internal.LangActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProtokitDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LangActivator.getInstance().getInjector(LangActivator.HU_BME_AUT_PROTOKIT_PROTOKITDSL);
	}
	
}
