/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.protokit.tests

import com.google.inject.Inject
import hu.bme.aut.protokit.model.ProtocolModel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ProtokitDSLInjectorProvider)
class ProtokitDSLParsingTest{

	@Inject
	ParseHelper<ProtocolModel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
