/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.protokit.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractProtokitDSLScopeProvider extends DelegatingScopeProvider {
}
